version: '3.9'
services: 
  mongo:
    image: mongo:4.2.23-bionic
    container_name: ms_mongo
    env_file: .env/mongo.env
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db/:/data/db
      - ./mongo/config/:/data/configdb
    networks:
      - ms
  mysql:
    image: mysql:8.0.31-debian
    container_name: ms_mysql
    env_file: .env/mysql.env
    ports:
      - 3306:3306
    volumes: 
      - ./mysql/:/var/lib/mysql
    networks:
      - ms
      
networks:
  ms:

  # mysql: